### ISSUE TITLE
Savannah map armory doors cannot be opened by riflemen

### ISSUE THREAD

**Issue by Froffy025** [CM-14/CM-14#1137]
## Description

**Reproduction**

spawn in savannah as rifleman
try to enter armory
beeptwice sound effect

**Screenshots**

![image](https://github.com/CM-14/CM-14/assets/78222136/c90abe77-885a-415b-b1df-fbe9db59300a)
he craves the rifle

**Additional context**

i just gotta replace the lock doors with common lock doors lol

**Comment by QuietlyWhisper** [comment]
@Tunguso4ka ur map

**Comment by Tunguso4ka** [comment]
> @Tunguso4ka your map
> 
> Might be door permissions issue but worth checking

I kinda know why. This door needs Alpha access, but we currently dont have squads so Rifleman and others NCO's dont get squad accesses by default.

**Comment by QuietlyWhisper** [comment]
It should be resolved when smug commits squads then I think..

**Comment by QuietlyWhisper** [comment]
requires 
- #218

**Comment by DrSmugleaf** [comment]
Done in https://github.com/CM-14/CM-14/commit/28629cb07033089bc78e213146bb27f91bb78c43
