### ISSUE TITLE
M276 Pattern Ammo Load Rig can't store magazines

### ISSUE THREAD

**Issue by Froffy025** [CM-14/CM-14#1143]
## Description

**Reproduction**

equip M276 Pattern Ammo Load Rig
try to store magazine
This doesn't go there!
**Screenshots**

![image](https://github.com/CM-14/CM-14/assets/78222136/f9796c94-dc56-454b-bb88-923ff9b8c1b1)

**Additional context**

seems important

**Comment by QuietlyWhisper** [comment]
https://github.com/CM-14/CM-14/pull/1157
