### ISSUE TITLE
fix pistol sizes

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#1145]
looks silly
![image](https://github.com/CM-14/CM-14/assets/121047731/d6298f80-36dc-4437-8868-4fe1c0412f03)

**Comment by Froffy025** [comment]
this is easy. you want that bad boy 2x2 square? i can do it rq

**Comment by QuietlyWhisper** [comment]
> this is easy. you want that bad boy 2x2 square? i can do it rq

make it a 2x3, will be doing big size fixes later

**Comment by QuietlyWhisper** [comment]
https://github.com/CM-14/CM-14/pull/1157
