### ISSUE TITLE
starting/spawn loadouts should be "basic"

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#1571]
when spawning from cryo, you only have your uniform and a satchel and ID/tags, and get everything else from the vendors.

Also bonus points if you figure out how to spawn a person starting hungry

**Comment by DrSmugleaf** [comment]
Done in https://github.com/CM-14/CM-14/pull/2055 and https://github.com/CM-14/CM-14/pull/2037
