### ISSUE TITLE
TODO list for first playtest

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#16]
[See completed issues in comment below.](https://github.com/CM-14/CM-14/issues/16#issuecomment-1809686890)

---

**Comment by QuietlyWhisper** [comment]
please comment on the issue if you're working on something

**Comment by QuietlyWhisper** [comment]
anything not listed here should be on #492

**Comment by QuietlyWhisper** [comment]
All mp roles are essentially done and are just waiting on me to finish #30

**Comment by Tunguso4ka** [comment]
why was it unpinned?

**Comment by DrSmugleaf** [comment]
> why was it unpinned?

Missclicked it on my phone

**Comment by Tunguso4ka** [comment]
there are no synthetic roles in the list. Will we be adding them?

**Comment by QuietlyWhisper** [comment]
> there are no synthetic roles in the list. Will we be adding them?

probably a thing for the second playtest if there's interest

**Comment by JoeHammad1844** [comment]
once everything needed for mapping is done ill probably try my hand at it

**Comment by JoeHammad1844** [comment]
#773

**Comment by Tunguso4ka** [comment]
#800

**Comment by JoeHammad1844** [comment]
#813

**Comment by QuietlyWhisper** [comment]
moved because it will be CBT to go back and fix all the yml for construction if these aren't done
- #746

**Comment by Terraspark4941** [comment]
close and de-pin, as first playtest is now complete?
