### ISSUE TITLE
Engineering Radio Encryption Key

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#1617]

**Comment by DangerRevolution** [comment]
do you want these the same colour as the CM13 variants? should these be new keys or overwrites of base game keys?

**Comment by QuietlyWhisper** [comment]
> do you want these the same colour as the CM13 variants? should these be new keys in a CM folder or overwrites of base game keys?

Just remember they were already implemented while I was looking into answering!
![image](https://github.com/CM-14/CM-14/assets/121047731/862e6c2a-18d9-4da9-8568-d0d0d010bb56)
![image](https://github.com/CM-14/CM-14/assets/121047731/0751fb68-0680-4ae9-9328-60211e1f736d)
