### ISSUE TITLE
The playtest game map

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#17]

**Comment by QuietlyWhisper** [comment]
MALO is currently working on this.

**Comment by Tunguso4ka** [comment]
> when all the mapping stuff is ready i would like to try my hand

WO is already assigned to the Malo.

**Comment by QuietlyWhisper** [comment]
> thats fine, I could do the ERT shuttles, maybe a full map

If you want to do a full map check out 
- #496 
I think anything related to mapping was probably pinned in the development channel

**Comment by MaloTV** [comment]
> Contributor i shall take a 2 day break for personall reasons

**Comment by QuietlyWhisper** [comment]
A map is currently planned for the first playtest.

**Comment by MaloTV** [comment]
QUack
