### ISSUE TITLE
combat knife

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#198]
- [ ] sprites
- [ ] yml
- [ ] sounds

**Comment by Aexxie** [comment]
Combat Knife already exists in upstream: [Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml](https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml)

**Comment by QuietlyWhisper** [comment]
> Combat Knife already exists in upstream
This was supposed to be the issue for the boot knife
