### ISSUE TITLE
Smoke coming through the wall

### ISSUE THREAD

**Issue by MetalSage** [CM-14/CM-14#2064]
## Description

If you fire a smoke grenade from the grenade launcher at the wall behind which there is a void, the smoke will pass through the wall. 

**Reproduction**

1. Take WeaponLauncherM92 and M40Smoke
2. Unload the grenade launcher
3. Load the grenade launcher with a smoke grenade
4. Shoot at the wall behind which there is nothing

**Screenshots**

https://github.com/CM-14/CM-14/assets/74924875/a2c48f45-96bc-4c59-a44f-8fd82cfaca65

**Additional context**

**Comment by DrSmugleaf** [comment]
This won't be a problem live since explosions won't be able to create vacuums (see https://github.com/space-wizards/space-station-14/pull/27548)
Upstream though, explosions should probably be changed to not break tiles under walls.
