### ISSUE TITLE
Medical roles should be able to change the holocard of a marine in the health analyzer UI

### ISSUE THREAD

**Issue by DrSmugleaf** [CM-14/CM-14#2172]

**Comment by blueDev2** [comment]
Does a holocard system currently work or even exist?

**Comment by DrSmugleaf** [comment]
> Does a holocard system currently work or even exist?

Not yet

**Comment by blueDev2** [comment]
Is it okay to allow anyone using a medical scanner or medHUD to change holocards or should there be a skill check?

**Comment by DrSmugleaf** [comment]
> Is it okay to allow anyone using a medical scanner or medHUD to change holocards or should there be a skill check?
There should be a skill check, in cm13 it requires level 2 in medical skill.

**Comment by blueDev2** [comment]
When should the hud show a red skull? I've seen it a few times and I think it's related to holocards, but never understood the specifics.
