### ISSUE TITLE
Squad spawn points (alpha/bravo/charlie/delta)

### ISSUE THREAD

**Issue by DrSmugleaf** [CM-14/CM-14#218]
This issue should also resolve
- #1137

**Comment by QuietlyWhisper** [comment]
This should be done with cyrosleep spawns

See rain's ekrixi fork for example

**Comment by QuietlyWhisper** [comment]
This issue should resolve
- #1137 when completed

**Comment by DrSmugleaf** [comment]
Done in https://github.com/CM-14/CM-14/pull/1916 and https://github.com/CM-14/CM-14/commit/380284bd9c1a2d9187479395c71e17dd59e07877
