### ISSUE TITLE
All shoes need noslip

### ISSUE THREAD

**Issue by Skarletto** [CM-14/CM-14#2192]
## Description

Slipping is cringe. Also only happens when you take your shoes off on cm13

**Comment by DrSmugleaf** [comment]
Marines were made immune to slipping in https://github.com/CM-14/CM-14/commit/3be54a1809204a5a6bd4ac51d934c71b2a7566e8 already
Is there anything that should be able to slip them?

**Comment by Skarletto** [comment]
Oh I did not see that PR

Marines who take their shoes off can slip on the banana peel on LV :trollface: but it's not a used mechanic besides that
LGTM then
