### ISSUE TITLE
[BUG] Rifle sprite does not update to empty at auto mag eject

### ISSUE THREAD

**Issue by amo020** [CM-14/CM-14#2237]
## Description
When the auto eject throw when firing the last round of a magazine the rifle magazine sprite layer is not hidden.

## Step to reproduce
* Have a magazine with only one cartridge
* Load a rifle with the 1 cartridge magazine
* Fire the rifle

**Screenshots**
Recording:

https://github.com/CM-14/CM-14/assets/167775671/66e1f8d3-0db8-4769-b741-93d6fd43113f

## Test matrices  :
| commit # | Reproduced? |
| --- | --- |
| CM14 3be54a1809204a5a6bd4ac51d934c71b2a7566e8 | No |
|CM14 94a113dbd6a076d199591eefb7875f91e9f7c463 | Yes |
| SS14 ec5a3b0fd2c56749e0addddacc90caf6ff002078 | Yes |
| SS14 f933922c9e7e561b83daea356450755e4ee830a3  | Yes |
| SS14 d36ff569ab65692dffdc8a0ac8c7d8b8655bff46  | Yes |
| CM14 ca5bf41ff1df8d4d7d2e8e3d907590274b328cbc | Yes |

Note that if you fire again with the "phantom" magazine the sprite get updated now.

**Comment by geraeumig** [comment]
This seems like an upstream bug, just replicated on the upstream repo.

**Comment by amo020** [comment]
@geraeumig i did not reproduced the issue on https://github.com/space-wizards/space-station-14/commit/f933922c9e7e561b83daea356450755e4ee830a3 nor on https://github.com/space-wizards/space-station-14/commit/d36ff569ab65692dffdc8a0ac8c7d8b8655bff46

**Comment by amo020** [comment]
But the way you reproduced it is interesting.

**Comment by geraeumig** [comment]
Created a PR to fix the issue, will recheck again if the issue is from the upstream on https://github.com/space-wizards/space-station-14/commit/f933922c9e7e561b83daea356450755e4ee830a3

**Comment by geraeumig** [comment]
Replicated on https://github.com/space-wizards/space-station-14/commit/f933922c9e7e561b83daea356450755e4ee830a3

https://github.com/CM-14/CM-14/assets/171753363/245631d8-b89e-442e-a9f6-33639c00696f

**Comment by amo020** [comment]
I got confused because of the chambered round. But you are right.
