### ISSUE TITLE
make sure marines can't hear queen's word

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#2239]

**Comment by QuietlyWhisper** [comment]
supposedly this happens in downstream, so this really just needs to be tested on master and fixed if it is broken.

**Comment by MetalSage** [comment]
> supposedly this happens in downstream, so this really just needs to be tested on master and fixed if it is broken.

I checked the bug on the master branch of this repository, the bug is also here

https://github.com/CM-14/CM-14/assets/74924875/49c6c79c-fa18-43af-9cae-fa9cf3e0a528

**Comment by DrSmugleaf** [comment]
This isn't a problem here, word of the queen explicitly filters for xenos of the same hive, which works properly under the distress signal gamerule.
Either way, I added another check for forks that don't run this in https://github.com/CM-14/CM-14/commit/bd5157a0f7a902d9086e80a0f7c50ecff8aec0a4
![image](https://github.com/CM-14/CM-14/assets/10968691/792c232e-a912-40ec-a273-bb1a7cecb5b4)
