### ISSUE TITLE
Xenomorph weed can spread to the Abyss Tiles

### ISSUE THREAD

**Issue by MetalSage** [CM-14/CM-14#2240]
## Description

The xeno weeds may extend to the Tails of the Abyss.
If you try to put XenoWeedsSource next to Abyss or CMCargoElevator, it will spread to them without any problems

**Reproduction**

- Plant xeno weeds next to the abyss or CMCargoElevator.
- Observe

**Screenshots**

![image](https://github.com/CM-14/CM-14/assets/74924875/7d55ce3e-0743-4ddb-aa82-9af7e51f6ca6)

**Additional context**

**Comment by DrSmugleaf** [comment]
This is fixed now, any elevators need to have a tile under them that prevents weed spread, such as CMFloorSteelNoWeeds
