### ISSUE TITLE
The xenomorph weed has a restriction on simultaneous propagation

### ISSUE THREAD

**Issue by MetalSage** [CM-14/CM-14#2241]
## Description

The xenomorph herb has a limit on simultaneous distribution.
If you try to place multiple sources of xenomorph grass, they will all spread very slowly

**Reproduction**

- Put in one source of xenomorph weed.
- Monitor the rate of spread
- Place 20-40 more xenomorph weed sources for more visibility.
- Monitor the rate of spread

**Screenshots**

https://github.com/CM-14/CM-14/assets/74924875/3d5e49d3-9443-46a7-8bff-39f6f7d8239c

https://github.com/CM-14/CM-14/assets/74924875/cb3886d4-8676-41d1-a012-7e5f1586c70e

**Additional context**

**Comment by DrSmugleaf** [comment]
This is because of the way edge spreader updates work upstream, I didn't fix it yet since I didn't think it would be a major problem after round start.
I hotfixed it now in https://github.com/CM-14/CM-14/commit/e79e3cff8b0a48d50a799d50d23053182d789578
