### ISSUE TITLE
All barricades cannot be placed at an angle

### ISSUE THREAD

**Issue by MetalSage** [CM-14/CM-14#2313]
## Description

All barricades cannot be placed at an angle. If you try to build a barricade through the construction menu, it will always be facing south

**Reproduction**

- Open the construction menu
- Build a barricade at an angle other than south

**Screenshots**

https://github.com/CM-14/CM-14/assets/74924875/aba42b0d-3799-4bab-849b-c05b1e72ac61

**Additional context**

**Comment by UbaserB** [comment]
this is actually a wizden issue to some degree right now
