### ISSUE TITLE
Wielding a gun makes you lose a bullet.

### ISSUE THREAD

**Issue by DangerRevolution** [CM-14/CM-14#2343]
## Description

Read below.
**Reproduction**

Wield a gun using Z.
Lose one bullet out of mag.

**Comment by SphiraI** [comment]
This was verified to be a client-side misprediction. No bullet is lost, it just looks like it is.

**Comment by geraeumig** [comment]
Upstream misprediction bug, happens around [here](https://github.com/space-wizards/space-station-14/blob/c79384c5fd0156cea5db6db9576674fab28e534c/Content.Shared/Inventory/VirtualItem/SharedVirtualItemSystem.cs#L219).
On the client's side spawning a virtual item will always fail, which in turn makes the `UseInHandEvent` handling to fail too - that passes the unhandled event to the [gun system](https://github.com/space-wizards/space-station-14/blob/1aa5e023d4b30c05b715a92c07a47f26a0b26f70/Content.Shared/Wieldable/WieldableSystem.cs#L40), which proceeds to cycle the gun only on client's side.

**Comment by QuietlyWhisper** [comment]
- #2456
