### ISSUE TITLE
Dead xeno still visible on the "watch mother ability"

### ISSUE THREAD

**Issue by UnicornOnLSD** [CM-14/CM-14#2363]
## Description

As a xeno when you use the ability to spectate other members of the hive, dead xenoes show up, while they shouldn't, it's a known bug but putting it here so sure it's seen
**Reproduction**

1. Be xeno
2. Use ability to watch mother etc
3. click a xeno realise it's dead

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/CM-14/CM-14/commit/e1ed76a5c23ba3f162f36f4ebef2ef4239f881a1
