### ISSUE TITLE
Bloodloss is much too strong.

### ISSUE THREAD

**Issue by Skarletto** [CM-14/CM-14#2365]
## Description

We almost ran out of blood packs, and some marines even reached 0% blood. I have literally only seen this happen once in CM13. The worst I see it get is like, 30%. Most marines had major bloodloss during the playtest.

**Comment by lunarcomets** [comment]
mostly for posterity's sake but: vendors apparently currently are dispensing blood_packs_ from upstream, not the iv compatible blood bags which are designed to be used with the doubled blood pool of marines (300u to 600u), so this was part of the issue of bloodloss

blood bags are also supposed to be able to be applied to people directly without an iv, but appears to not be implemented yet which is funnn

**Comment by QuietlyWhisper** [comment]
We need to look into bleed wound stacking again, I think marines are probably bleeding too much
