### ISSUE TITLE
Comtechs need to spawn with insuls

### ISSUE THREAD

**Issue by Skarletto** [CM-14/CM-14#2372]

**Comment by DrSmugleaf** [comment]
@Skarletto Is this on round-start or on an old version? They don't for me locally, though they can get some in their vendor.
![image](https://github.com/CM-14/CM-14/assets/10968691/491be426-add8-4690-8ba6-06731f1105f6)

**Comment by DrSmugleaf** [comment]
Ok I see the confusion I forgot to add it to the vendor, not that they come out of cryo with them
