### ISSUE TITLE
Xeno walls should be breakable faster

### ISSUE THREAD

**Issue by Skarletto** [CM-14/CM-14#2374]
It takes 5 thousand years for a marine to break them, on CM it takes less than 10 knife hits.

**Comment by Tunguso4ka** [comment]
Currently we have the same structure's health numbers as in cm13
```
#define HEALTH_WALL 3000
#define HEALTH_WALL_REINFORCED 9000
#define HEALTH_WALL_XENO 900
#define HEALTH_WALL_XENO_WEAK 100
#define HEALTH_WALL_XENO_THICK 1350
#define HEALTH_WALL_XENO_MEMBRANE 300
#define HEALTH_WALL_XENO_REFLECTIVE 300 
#define HEALTH_WALL_XENO_MEMBRANE_THICK 600

#define HEALTH_DOOR 1200
#define HEALTH_DOOR_XENO 600
#define HEALTH_DOOR_XENO_THICK 900
```
`code/__DEFINES/conflict.dm` line 242

Using simple math and M5 knife (24 damage):

- It takes `36` hits to destroy resin wall (HEALTH_WALL_XENO 900)
- It takes `24` hits to destroy resin door (HEALTH_DOOR_XENO 600)
