### ISSUE TITLE
Huggers cannot hug without assistance

### ISSUE THREAD

**Issue by c0rigin** [CM-14/CM-14#2378]
Huggers are unable to hug hosts unless a drone puts the hugger on.

**Comment by Skarletto** [comment]
Not a bug, you can't hug from 5 miles away; you need to be right next to them, the same way it is on cm13
The range is *very* short
Unless you mean it's something else

https://github.com/CM-14/CM-14/assets/122584947/6faccb3d-582a-4179-8ba3-8e91e0f893af



https://github.com/CM-14/CM-14/assets/122584947/b778dce1-53f5-42db-a86a-165f4b30e39f

**Comment by c0rigin** [comment]
Clarification, huggers cannot hug people in crit no matter the range, requiring a drone to put them on instead.

**Comment by DrSmugleaf** [comment]
Tested locally and I think the confusion is that you can't drag yourself to hug, only clicking works.
This is fixed now in https://github.com/CM-14/CM-14/commit/8ee24441bf718718ada8a7ae156826f6970b9dbd
