### ISSUE TITLE
De/Construction inconsistencies

### ISSUE THREAD

**Issue by WarMechanic** [CM-14/CM-14#2389]
- CM14 reinforced girders turn into SS14 steel sheets when destroyed.
- Barricades give 2 metal when deconstructed, and 3 when destroyed.

**Comment by Siigiil** [comment]
There's also a bunch of weirdness with construction and deconstruction in general, like rwalls turning directly into normal girders instead of reinforced ones. I'll handle this one and probably bring the actual construction steps and material costs in line with CM13.
