### ISSUE TITLE
Xenos don't have their deathgasp

### ISSUE THREAD

**Issue by Randomplayer2or3** [CM-14/CM-14#2494]
## Description
Accidentally posted this to upstream repo, whoops.

**Comment by QuietlyWhisper** [comment]
Can you be more specific? Some of the xenos appear to have death sounds so I'm not sure what you're referring to

**Comment by Randomplayer2or3** [comment]
Based on playtest recordings, xenos have the default deathgasp of "(XX-121) seizes up and falls limp, its eyes dead and lifeless..." instead of cm13's "(XX-121) lets out a waning gluttural screech, green blood bubbling from its maw..."

**Comment by QuietlyWhisper** [comment]
![image](https://github.com/CM-14/CM-14/assets/121047731/072cdc7b-a37b-49fc-b88b-b0c474a35f74)
Thanks
