### ISSUE TITLE
Sandbags

### ISSUE THREAD

**Issue by c0rigin** [CM-14/CM-14#485]
- [x] Sprites https://github.com/CM-14/CM-14/pull/674
- [x] Yaml https://github.com/CM-14/CM-14/pull/674
- [ ] Filling with entrenching tool

**Comment by JoeHammad1844** [comment]
you forgot 
* [ ] barbed wire

**Comment by QuietlyWhisper** [comment]
> you forgot
> 
> * [ ]  barbed wire

- #486
