### ISSUE TITLE
Combat tech buildings

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#493]
- [x] #670
- [x] #485
- [x] #486

**Comment by Tunguso4ka** [comment]
> Is there are CM-14 specific discord? 

there are.

https://discord.com/invite/cBJdrGeS

**Comment by QuietlyWhisper** [comment]
> I am working on this, ended up being a lot more complex than I thought. Is there are CM-14 specific discord? Barricades and upgrades are done though!
> 
> On that note, no idea how to code a radial menu into SS14 like in CM14 for wall upgrades. 

@DrSmugleaf this can use the same ui as xeno yeah?

**Comment by DrSmugleaf** [comment]
> > I am working on this, ended up being a lot more complex than I thought. Is there are CM-14 specific discord? Barricades and upgrades are done though!
> > On that note, no idea how to code a radial menu into SS14 like in CM14 for wall upgrades.
> 
> @DrSmugleaf this can use the same ui as xeno yeah?

Yeah for now it can be a list of upgrades in a pop-up window like ordering construction and choosing resin structure for drones/hivelords/queen

For radials specifically I'd need to add support for them which would take a while

**Comment by Tunguso4ka** [comment]
> link dead, please send a new one

https://discord.gg/mjpJk2ueDY
