### ISSUE TITLE
Riot Helmet

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#550]
https://cm-ss13.com/wiki/Marine_Equipment#Riot_Helmet

**Comment by Aexxie** [comment]
"Light" riot gear exists in upstream. Could add heavy?

**Comment by QuietlyWhisper** [comment]
It needs to be done regardless, balancing between upstream and cm wont be the same. I dont think heavy riot armor is needed either because its either theyre in their mp armor or riot armor.

**Comment by Aexxie** [comment]
So make a separate version?

**Comment by QuietlyWhisper** [comment]
Pretty much. If it uses the same sprite as upstream like the security bag did, then youd just need to make it a child and add the values or whatever

**Comment by QuietlyWhisper** [comment]
We're not actually overwriting anything, since the .yml file is named differently and the item should have a unique ID

So you want to put this in some sort of armors folder in the _cm14 prototypes which I think already exists, and then either add to an existing file or create a new one like "Cm riot gear"

If the sprite is the same you can just do something like
parent: riotgearid
And it will inherit everything that makes up upstreams riot armor, and from there you can add the specific component that gives armor

**Comment by Aexxie** [comment]
Yeah that makes sense (at least if parent is a key in the yaml class.) I do want to get better at spriting and the upstream is a bit mid. Initial stats might be a bit scuffed because I don't know all of the ways it'll get used, but I will tweak it later on.
