### ISSUE TITLE
Tactical Medical Pouch

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#568]
https://cm-ss13.com/wiki/Marine_Equipment#Tactical_Medical_Pouch

**Comment by Aexxie** [comment]
I'm assuming this is just called "medical pouch" internally, so
https://github.com/CM-14/CM-14/pull/762

**Comment by Aexxie** [comment]
It was not.

**Comment by Tunguso4ka** [comment]
> It was not.

it was, #762 it has id CMPouchMedicalSoc

**Comment by Tunguso4ka** [comment]
#762
in Resources/Prototypes/_CM14/Entities/Objects/Clothing/pouches.yml on line 353 with id CMPouchMedicalSoc
