### ISSUE TITLE
ColMarTech automated marine  equipment rack

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#581]

**Comment by c0rigin** [comment]
I’ll take this issue.

**Comment by c0rigin** [comment]
I’m probably just going to add the weapon and armor vendors, and the fills for them too. IIRC those just dispensed onto the floor.

**Comment by c0rigin** [comment]
If we have a system for the point-buy vendors, I could probably add a few of those too.

**Comment by QuietlyWhisper** [comment]
> I’m probably just going to add the weapon and armor vendors, and the fills for them too. IIRC those just dispensed onto the floor.

feel free to add anything that can be done, systems can be done later as long as the fills are ready anyways
