### ISSUE TITLE
CPR

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#602]
Should start an interaction that when each repeated relatively quick doafter is completed, forces the targeted player to take a breath as if they were not in crit state

An early attempt to make this was in https://github.com/space-wizards/space-station-14/pull/19437
If this is completed, the finished product should be pushed upstream

This may conflict with @Jezithyr wound refactor however

**Comment by Hmeister-fake** [comment]
Delta-V has working CPR with a whole sprite for it. Maybe try to port it?

**Comment by QuietlyWhisper** [comment]
> Delta-V has working CPR with a whole sprite for it. Maybe try to port it?

I did try to port it, see the linked PR
It's not a great implementation because it isn't networked correctly + several bugs that were bandaid fixed

Unless they redid it again recently, CPR needs to be made from ground up according to @DrSmugleaf

**Comment by DrSmugleaf** [comment]
I haven't seen Delta-V's implementation of CPR recently, but there's not much of a point to copying the one that was closed upstream since the implementation is short enough and the code structure has enough mistakes that makes it easier to re-implement ourselves.
