### ISSUE TITLE
engineering tools

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#643]

**Comment by Aexxie** [comment]
What tools do we need

**Comment by gusxyz** [comment]
screwdriver, multitool, wirecutter, welding tool, crowbar, wrench. basically just all the tools that are in ss14

**Comment by gusxyz** [comment]
https://cm-ss13.com/wiki/Maintenance_Technician

**Comment by Aexxie** [comment]
so essentially just port sprites over? If that's it, I'll take care of this one

**Comment by QuietlyWhisper** [comment]
Pretty much!
For the yml its literally just setting the parent to the upstream item and giving it a cm description essentially
