### ISSUE TITLE
double doors

### ISSUE THREAD

**Issue by JoeHammad1844** [CM-14/CM-14#687]
they are everywhere
![image](https://github.com/CM-14/CM-14/assets/130668733/565a5654-ffa1-4102-a8d0-f44118d56940)
![image](https://github.com/CM-14/CM-14/assets/130668733/49452279-e163-4a6b-a544-401642066904)
![image](https://github.com/CM-14/CM-14/assets/130668733/dbbbb910-a193-4cdc-8f66-e580fb554f39)
![image](https://github.com/CM-14/CM-14/assets/130668733/dcfa0569-6bcd-46ad-b44e-ea72c239be8a)

**Comment by QuietlyWhisper** [comment]
you need to link these issues to #16 or they'll get lost, simply mention it in the description or comment on #16
