### ISSUE TITLE
some of the new tiles shows space under it

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#712]
![image](https://github.com/CM-14/CM-14/assets/121047731/e94316ce-77b4-41e8-b43d-6bd0aa69c40f)
`Why is the floor see trough oh god the space is here`

_Originally posted by @MaloTV in https://github.com/CM-14/CM-14/issues/709#issuecomment-1832473933_

**Comment by Tunguso4ka** [comment]
oh, fuck.

**Comment by QuietlyWhisper** [comment]
looks like this for the maints version too 
![image](https://github.com/CM-14/CM-14/assets/121047731/badaf8e4-4867-4315-9c37-0b96d3ef3144)
