### ISSUE TITLE
fix layering issues

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#723]
All barricades and airlocks have bad layering problems with players;

![image](https://github.com/CM-14/CM-14/assets/121047731/9c336680-ea69-4d46-83e2-49cdf92aa0a5)
![image](https://github.com/CM-14/CM-14/assets/121047731/26a476be-0e48-4a30-9adc-b8b18553d29a)
![image](https://github.com/CM-14/CM-14/assets/121047731/6876a241-5378-4ab9-ba5f-17f9e87cc1f5)

**Comment by Tunguso4ka** [comment]
also headset on moths are also broken.

**Comment by QuietlyWhisper** [comment]
> also headset on moths are also broken.

it seems like clothing on moths in general is broke. have you seen the odd look of gloves?
