### ISSUE TITLE
add all mp roles

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#74]
- [ ] #75
- [ ] #76
- [ ] #77

**Comment by Tunguso4ka** [comment]
i take this

**Comment by QuietlyWhisper** [comment]
This file should contain all their relevant access and starting equipment, the spawnpoint sprites should already be in the repo so just follow the format of the existing roles pretty much
https://github.com/cmss13-devs/cmss13/blob/fcac33e0b81d80f57363cdc5e12dbb3a2dbde39c/code/modules/gear_presets/uscm_police.dm

**Comment by QuietlyWhisper** [comment]
Loadouts cant be considered completed until access is finished

**Comment by Tunguso4ka** [comment]
> Loadouts cant be considered completed until access is finished

also radios.
