### ISSUE TITLE
materials

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#746]
we need material stacks.
- [x] #955
- [x] plasteel #865
- [x] steel https://github.com/CM-14/CM-14/pull/809
- [x] #855

**Comment by QuietlyWhisper** [comment]
Since cm13 doesnt have wires that kind of works out thankfully

**Comment by Tunguso4ka** [comment]
> Since cm13 doesnt have wires that kind of works out thankfully

![зображення](https://github.com/CM-14/CM-14/assets/71643624/f8aa259b-0951-474b-812b-bd8b53fea5a5)

**Comment by QuietlyWhisper** [comment]
Yeah I figured it makes more sense to keep upstream complete wires anyway, they don't look out of place honestly
