### ISSUE TITLE
CPR cannot be performed anymore on target if canceled 

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#769]

**Comment by QuietlyWhisper** [comment]
@DrSmugleaf

**Comment by coolmankid12345** [comment]
I went to go check this one to fix but I can't seem to replicate it

**Comment by QuietlyWhisper** [comment]
Iirc it happened when I was doing cpr and then moved out of range, it left the target in the "theyre already recieving cpr!" State
