### ISSUE TITLE
Decals

### ISSUE THREAD

**Issue by DrSmugleaf** [CM-14/CM-14#796]
- [x] Alpha/Bravo/Charlie/Delta tiles https://github.com/CM-14/CM-14/pull/758
- [x] Green tiles https://github.com/CM-14/CM-14/pull/758
- [x] Medical tiles https://github.com/CM-14/CM-14/pull/758
- [x] Cargo tiles https://github.com/CM-14/CM-14/pull/758
- [x] Office tiles https://github.com/CM-14/CM-14/pull/758
- [x] Silver tiles https://github.com/CM-14/CM-14/pull/758
- [x] Striped tiles https://github.com/CM-14/CM-14/pull/758
- [x] Telecommunications tiles https://github.com/CM-14/CM-14/pull/758
- [x] Hazard tiles https://github.com/CM-14/CM-14/pull/758
- [x] Sterile tiles https://github.com/CM-14/CM-14/pull/758
- [x] White tiles https://github.com/CM-14/CM-14/pull/758
- [x] Wood tiles https://github.com/CM-14/CM-14/pull/758
- [x] WY tiles https://github.com/CM-14/CM-14/pull/758
- [x] Big USCM logo https://github.com/CM-14/CM-14/pull/741

**Comment by Tunguso4ka** [comment]
Im already added USCM Logo in #741 as a decal.

**Comment by DrSmugleaf** [comment]
> Im already added USCM Logo in #741 as a decal.

Ah I missed it, thanks!
