### ISSUE TITLE
Radio sprite

### ISSUE THREAD

**Issue by DrSmugleaf** [CM-14/CM-14#834]

**Comment by Tunguso4ka** [comment]
I ported all radio headsets and keys in PR #607.

So all that left to port is intercom, beacon and walkie talkie (/icons/obj/items/radio.dm)
![зображення](https://github.com/CM-14/CM-14/assets/71643624/c683942a-4b62-4a8f-a4c6-c56e74318903)

**Comment by QuietlyWhisper** [comment]
#980 Resolves this I think
