### ISSUE TITLE
Clothing crates

### ISSUE THREAD

**Issue by DrSmugleaf** [CM-14/CM-14#911]
- [ ] Large Pouch 2x(pistol,magazine,general) Cost: $2000
- [ ] medical pouches crate (1x firstaid, medical, syringe, medkit, autoinjector) Cost: $2000
- [ ] Webbing Crate (x4) Cost: $2000 (this should be changed to two of each webbing(brown/black) later)

**Comment by Verification31** [comment]
Shouldn't Brown and Black Webbing Crate be moved to the second playtest? Black Webbing is listed under the second playtest, so it doesn't make sense for a crate that contains black webbing to be in the first playtest.

**Comment by Verification31** [comment]
The same should be done with the Shoulder Holster Crate, the Knife Vest Crate, and the Drop Pouch Crate. They are both on the list for the improved second playtest and shouldn't be on here. I apologize for not mentioning this in my original comment, I just didn't notice at the time.
