### ISSUE TITLE
Magazine Updates - Before First Playtest

### ISSUE THREAD

**Issue by Aexxie** [CM-14/CM-14#936]
## Description

As requested in [Pull #935](https://github.com/CM-14/CM-14/pull/935), I need someone to update several magazine capacities to their intended values. I also need a cartridge sprite for .44 bullets.

Checklist:
- [ ] Update capacity of `CMMagazineExtendedRifleM41A`
- [ ] Update capacity of `CMMagazineRifleM4RA`
- [ ] Update capacity of `CMMagazineRifleExtendedM4RA`
- [ ] Update capacity of `CMMagazineExtendedCaselessM39`
- [ ] M44 Bullet (.44) - Will need to update line 28 in `Resources/Prototypes/_CM14/Entities/Objects/Weapons/Guns/Ammunition/SpeedLoaders/revolver.yml` accordingly.

**Comment by QuietlyWhisper** [comment]
#16

**Comment by z9ctn4fn** [comment]
Aye. I'll get on it.

**Comment by Aexxie** [comment]
> #16

Right, I just have a specific list of things here so I can keep my own thoughts organized.

**Comment by DrSmugleaf** [comment]
Fixed in https://github.com/CM-14/CM-14/pull/943 and https://github.com/CM-14/CM-14/commit/b4b87bce65f81ee6eff8b88f4d99a3111367d83f

**Comment by Aexxie** [comment]
> Fixed in #943 and [b4b87bc](https://github.com/CM-14/CM-14/commit/b4b87bce65f81ee6eff8b88f4d99a3111367d83f)

Awesome, thanks. I think the bullet itself still needs a prototype & sprite, I think I set up the tag so it should work when added. The cartridge type will still need to be changed in line 28 whenever it is added, because currently the speedloader is filled with standard .45s.

**Comment by DrSmugleaf** [comment]
> > Fixed in #943 and [b4b87bc](https://github.com/CM-14/CM-14/commit/b4b87bce65f81ee6eff8b88f4d99a3111367d83f)
> 
> Awesome, thanks. I think the bullet itself still needs a prototype & sprite, I think I set up the tag so it should work when added. The cartridge type will still need to be changed in line 28 whenever it is added, because currently the speedloader is filled with standard .45s.

Done in https://github.com/CM-14/CM-14/commit/0f60a8f9629e8855e50ef09ed7b01f80e5187d6c, we don't have handfuls so we can't copy the sprites for those yet

**Comment by Aexxie** [comment]
> > > Fixed in #943 and [b4b87bc](https://github.com/CM-14/CM-14/commit/b4b87bce65f81ee6eff8b88f4d99a3111367d83f)
> > 
> > 
> > Awesome, thanks. I think the bullet itself still needs a prototype & sprite, I think I set up the tag so it should work when added. The cartridge type will still need to be changed in line 28 whenever it is added, because currently the speedloader is filled with standard .45s.
> 
> Done in [0f60a8f](https://github.com/CM-14/CM-14/commit/0f60a8f9629e8855e50ef09ed7b01f80e5187d6c), we don't have handfuls so we can't copy the sprites for those yet

On top of the game o7
