### ISSUE TITLE
Guns mispredict cycling a round when they shouldn't even attempt to

### ISSUE THREAD

**Issue by QuietlyWhisper** [CM-14/CM-14#992]
Wield gun
"cycled"
![image](https://github.com/CM-14/CM-14/assets/121047731/68b9101d-df2a-4a91-88e2-e1f6dd0748fe)

**Comment by DrSmugleaf** [comment]
Will be fixed in https://github.com/space-wizards/space-station-14/pull/26924

**Comment by QuietlyWhisper** [comment]
fixed
